# Fichier de configuration de workflow
on:
  push:
    branches:
      - main # déclenche lorsqu'une poussée est faite sur la branche main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # exécution sur un serveur ubuntu

    steps:
    - name: Checkout code # vérifie le code
      uses: actions/checkout@v2

    - name: Build and Test # construit et teste l'application
      run: |
        npm install
        npm run build
        
    - name: Deploy to server # déploie l'application sur le serveur
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }} # adresse IP du serveur
        username: ${{ secrets.SERVER_USERNAME }} # nom d'utilisateur pour se connecter au serveur
        password: ${{ secrets.SERVER_PASSWORD }} # mot de passe pour se connecter au serveur
        script: |
          # Fetching the git repositories
          sudo git fetch
          # Pulling the git repositories
          sudo git pull
          # Install all dependencies and build
          sudo ./install.sh
